package com.tutorial.ai.linkedin_agent.service;

import com.tutorial.ai.linkedin_agent.dto.News;
import com.tutorial.ai.linkedin_agent.external.LinkedInImageRegister;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

@Service
public class LinkedInImageUploadService {

    @Value("${app.upload.dir}")
    private String uploadDir;

    @Value("${person.urn}")
    private String personUrn;

    @Value("${oauth.token}")
    private String oauthToken;

    @Autowired
    private LinkedInImageRegister linkedInImageRegister;

    private String assetUrn;

    public Map<String,Object> registerImageOnLinkedIn(byte[] bytes){
        Map<String, Object> requestBody = Map.of(
                "registerUploadRequest", Map.of(
                        "recipes", List.of("urn:li:digitalmediaRecipe:feedshare-image"),
                        "owner", personUrn,
                        "serviceRelationships", List.of(Map.of(
                                "relationshipType", "OWNER",
                                "identifier", "urn:li:userGeneratedContent"
                        ))
                )
        );

        Map<String, Object> response = linkedInImageRegister.registerImage(requestBody, oauthToken);
        Map<String, Object> value = (Map<String, Object>) response.get("value");
         assetUrn = (String) value.get("asset");

        Map<String, Object> uploadMechanism = (Map<String, Object>) value.get("uploadMechanism");
        Map<String, Object> mediaUploadRequest = (Map<String, Object>) uploadMechanism.get("com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest");
        String uploadUrl = (String) mediaUploadRequest.get("uploadUrl");
        URI uploadUri = URI.create(uploadUrl);

        try{
//            byte[] imageAsBytes = getImageAsBytes(filename);
            linkedInImageRegister.uploadImage(uploadUri, "Bearer "+oauthToken,"application/octet-stream",bytes);
//            postImageOnLinkedIn("Feeling inspired after meeting so many talented individuals at this year's conference. #talentconnect");
            System.out.println("image uploaded successfully");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        return response;
    }

    public void postImageOnLinkedIn(News news){

        List<Map<String, Object>> mediaList = List.of(
                Map.of(
                        "status", "READY",
                        "description",Map.of(
                                "text","Center stage!"
                        ),
                        "media", assetUrn,
                        "title",Map.of(
                                "text","LinkedIn Talent Connect 2021"
                        )
                )
        );

        // Build the internal ShareContent
        Map<String, Object> shareContent = Map.of(
                "shareCommentary", Map.of("text", news.getTitle() + ".\n\n" +
                        news.getDescription().replaceAll(","," ") + ".\n\n" +
                        "This Post was generated by an AI Agent, please report to the account admin if you find any irrelevant content.\n\n" +
                        "#aiagents #linkedindevelopers #linkedinautomation"
                ),
                "shareMediaCategory", "IMAGE",
                "media", mediaList
        );

        // Build the top-level request body
        Map<String, Object> requestBody = Map.of(
                "author", personUrn,
                "lifecycleState", "PUBLISHED",
                "specificContent", Map.of(
                        "com.linkedin.ugc.ShareContent", shareContent
                ),
                "visibility", Map.of(
                        "com.linkedin.ugc.MemberNetworkVisibility", "PUBLIC"
                )
        );

        linkedInImageRegister.postImage("Bearer "+oauthToken,"2.0.0",requestBody);
    }

    private static String convertToBold(String text) {
        StringBuilder boldText = new StringBuilder();
        for (char c : text.toCharArray()) {
            if (c >= 'A' && c <= 'Z') {
                boldText.append((char) (c + 119809)); // Convert to bold uppercase
            } else if (c >= 'a' && c <= 'z') {
                boldText.append((char) (c + 119743)); // Convert to bold lowercase
            } else {
                boldText.append(c);
            }
        }
        return boldText.toString();
    }

    public byte[] getImageAsBytes(String fileName) throws IOException {

        Path filePath = Path.of(uploadDir, fileName);

        if (!Files.exists(filePath)) {
            throw new RuntimeException("File not found: " + fileName);
        }

        return Files.readAllBytes(filePath);
    }
}
